# Fandom page id can be found by:
# 1. Navigating to the page.
# 2. Clicking on the page's "History" tab.
# 3. Hovering over the "prev" link.

[database]
# https://superautopets.wiki.gg/wiki/Team_Names
# names_version = ?

# https://superautopets.wiki.gg/wiki/Pets
# pets_version = ?

# https://superautopets.wiki.gg/wiki/Food
# foods_version = ?

# https://superautopets.wiki.gg/wiki/Ailments
# ailments_version = ?

# https://superautopets.wiki.gg/wiki/Tokens
# tokens_version = ?

filename = "./sap.db"
# Avoid updating on startup as 100+ doctests will hit request limit for wiki.gg api.
update_on_startup = false

[general]
# Store battle data and build digraphs. If speed is necessary, this can be toggled off.
build_graph = true
