[package]
name = "sapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11", features = ["blocking"]}
scraper = "0.12.0"
rocket = "0.5.0-rc.2"
rusqlite = "0.25"
serde = {version = "1.0.147", features = ["derive"]}
serde_json = "1.0"
regex = "1.0"
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4.17"
log4rs = "1.2.0"

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.2"
features = ["sqlite_pool"]

[dependencies.rocket_contrib]
version = "0.4.11"
default-features = false
features = ["json"]