refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  scraper:
    kind: file
    path: "log/scraper.log"
    encoder:
      pattern: "{d} {l} {M} - {m}{n}"
  database:
    kind: file
    path: "log/db.log"
    encoder:
      pattern: "{d} {l} {M} - {m}{n}"
  dev:
    kind: file
    path: "log/dev.log"
    encoder:
      pattern: "{d} {l} {M} - {m}{n}"
loggers:
  db:
    level: debug
    appenders:
      - database
    additive: false
  wiki_scraper:
    level: info
    appenders:
      - scraper
    additive: false
  dev:
    level: info
    appenders:
      - dev
    additive: true
