refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  scraper:
    kind: file
    path: "log/scraper.log"
    encoder:
      pattern: "{d} {l} {M} - {m}{n}"
  database:
    kind: file
    path: "log/db.log"
    encoder:
      pattern: "{d} {l} {M} - {m}{n}"
  server:
    kind: file
    path: "log/server.log"
    encoder:
      pattern: "{d} {l} {M} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
loggers:
  api:
    level: info
    appenders:
      - server
    additive: false
  db:
    level: info
    appenders:
      - database
    additive: false
  wiki_scraper:
    level: info
    appenders:
      - scraper
    additive: false