refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  scraper:
    kind: file
    path: "log/scraper.log"
    encoder:
      pattern: "{d} {l} {M} - {m}{n}"
  database:
    kind: file
    path: "log/db.log"
    encoder:
      pattern: "{d} {l} {M} - {m}{n}"
  server:
    kind: rolling_file
    path: "log/server.log"
    encoder:
      pattern: "{d} {l} {M} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "logs/sapdb-service.{}.log"
root:
  level: info
  appenders:
    - server
loggers:
  api:
    level: info
    appenders:
      - server
    additive: false
  db:
    level: debug
    appenders:
      - database
    additive: false
  wiki_scraper:
    level: info
    appenders:
      - scraper
    additive: false
